[client]
showErrorDetails = true

#enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression=false

[browser]
gatherUsageStats = false

[theme]
primaryColor="#FF4B4B"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#31333F"
font="sans serif"